#define EDITOR_MODE

#define WINDOW_EDIT_SCREEN_WIDTH 1900
#define WINDOW_EDIT_SCREEN_HEIGHT 1000

#define WINDOW_GAME_SCREEN_WIDTH 1280
#define WINDOW_GAME_SCREEN_HEIGHT 720

#define GAME_RENDER_TARGET_WIDTH	WINDOW_GAME_SCREEN_WIDTH
#define GAME_RENDER_TARGET_HEIGHT	WINDOW_GAME_SCREEN_HEIGHT

#ifdef EDITOR_MODE
#define WINDOW_SCREEN_WIDTH		WINDOW_EDIT_SCREEN_WIDTH
#define WINDOW_SCREEN_HEIGHT	WINDOW_EDIT_SCREEN_HEIGHT
#else
#define WINDOW_SCREEN_WIDTH		WINDOW_GAME_SCREEN_WIDTH
#define WINDOW_SCREEN_HEIGHT	WINDOW_GAME_SCREEN_HEIGHT
#endif